name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Log in to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------------------
      # 4️⃣ Build & push app images
      # ---------------------------
      - name: Build and push vote image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_VOTE }}
          docker build -t $IMAGE_URI ./vote
          docker push $IMAGE_URI

      - name: Build and push worker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_WORKER }}
          docker build -t $IMAGE_URI ./worker
          docker push $IMAGE_URI

      - name: Build and push result image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_RESULT }}
          docker build -t $IMAGE_URI ./result
          docker push $IMAGE_URI

      # ---------------------------
      # 5️⃣ Deploy ECS services
      # ---------------------------

      # Deploy Redis
      - name: Deploy Redis service
        run: |
          aws ecs update-service \
            --cluster vote-app-cluster \
            --service redis \
            --force-new-deployment

      # Deploy Postgres
      - name: Deploy Postgres service
        run: |
          aws ecs update-service \
            --cluster vote-app-cluster \
            --service postgres \
            --force-new-deployment

      # Deploy Vote
      - name: Deploy vote service
        run: |
          aws ecs update-service \
            --cluster vote-app-cluster \
            --service vote \
            --force-new-deployment

      # Deploy Worker
      - name: Deploy worker service
        run: |
          aws ecs update-service \
            --cluster vote-app-cluster \
            --service worker \
            --force-new-deployment

      # Deploy Result
      - name: Deploy result service
        run: |
          aws ecs update-service \
            --cluster vote-app-cluster \
            --service result \
            --force-new-deployment
