name: Deploy to ECS

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4️⃣ Build, tag, and push vote image
      - name: Build and push vote image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_VOTE }}
          docker build -t $IMAGE_URI ./vote
          docker push $IMAGE_URI

      # 5️⃣ Build, tag, and push worker image
      - name: Build and push worker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_WORKER }}
          docker build -t $IMAGE_URI ./worker
          docker push $IMAGE_URI

      # 6️⃣ Build, tag, and push result image
      - name: Build and push result image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_RESULT }}
          docker build -t $IMAGE_URI ./result
          docker push $IMAGE_URI

      # 7️⃣ Deploy vote service
      - name: Deploy vote service
        run: |
          aws ecs update-service \
            --cluster vote-app-cluster \
            --service vote-service \
            --force-new-deployment

      # 8️⃣ Deploy worker service
      - name: Deploy worker service
        run: |
          aws ecs update-service \
            --cluster vote-app-cluster \
            --service worker-service \
            --force-new-deployment

      # 9️⃣ Deploy result service
      - name: Deploy result service
        run: |
          aws ecs update-service \
            --cluster vote-app-cluster \
            --service result-service \
            --force-new-deployment
